### PR TITLE
typo

### PR DESCRIPTION
**Pull request by jcamenisch**

### CODE REVIEW

**Comment by jhilden** [comment]
Thanks for the little fix.

What do you think of SMURF and Smurfville so far?   We are always eager to get any sort of feedback.

**Comment by jcamenisch** [comment]
I love the concept of building structure and good practices into the tooling. LOVE it. But, to be honest, I haven't taken time to dive into the implementation—or even install it on a project. I'm working full time on a WordPress plugin right now, and need to try to forget for a while how much I miss Rails. :(

**Comment by jhilden** [comment]
Oh noes. Stuck in only WordPress Development ;)

Let us know if you ever get the chance to try it out.

btw:  Just out of curiousity, how/where did you hear about this project?

**Comment by jcamenisch** [comment]
I can't find it for the life of me. It was mentioned in an article that I read yesterday, but I can't dig it up from history on my laptop or my phone. Nor can I even remember the topic of the article!

Anyway, glad I clicked the link.

**Pull request merged**
